name: Production deployment from master

on: 
  push:
    branches:
      - master

env:
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_PROD_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PROD_PASSWORD }}
  DBT_PROFILE_HOST:              localhost
  DBT_PROFILE_DB:                analytics

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt
        pip install dbt-mysql
    - name: Deploy
      run: |
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles
